"""Report generation: JSON, Markdown and HTML output."""

from __future__ import annotations

import dataclasses
import json

from .models import CostReport


def to_json(report: CostReport) -> str:
    return json.dumps(dataclasses.asdict(report), indent=2, default=str)


def to_markdown(report: CostReport) -> str:
    md = ["# Azure Cost Forecasting Report\n"]
    md.append(
        f"**Generated:** {report.generated_at}  \n"
        f"**Subscription:** `{report.subscription_id}`  \n"
        f"**History:** {report.history_days} days  \n"
        f"**Currency:** {report.currency}\n"
    )
    md.append("---\n\n## Historical Summary\n")
    md.append(
        f"| Metric | Value |\n|---|---|\n"
        f"| Average daily cost | {report.average_daily_cost:.2f} |\n"
        f"| Total cost ({report.history_days}d) | {report.total_historical_cost:.2f} |\n"
    )

    md.append("---\n\n## Cost Forecast\n")
    md.append("| Horizon | Projected Total | vs. Baseline | Trend |\n|---|---|---|---|\n")
    for fr in [report.forecast_30, report.forecast_60, report.forecast_90]:
        sign = "+" if fr.projected_total_vs_baseline >= 0 else ""
        md.append(
            f"| {fr.horizon_days} days | {fr.projected_total:.2f} | "
            f"{sign}{fr.projected_total_vs_baseline:.2f} | "
            f"{fr.trend_direction} ({fr.trend_percent_per_day:+.3f}%/day) |\n"
        )

    md.append("---\n\n## Cost Optimization Recommendations\n")
    if not report.recommendations:
        md.append("No optimization opportunities identified.\n")
    else:
        md.append(
            f"**Total estimated monthly saving: {report.total_estimated_monthly_saving:.2f}**\n\n"
        )
        md.append("| Severity | Category | Service | Est. Monthly Saving | Description |\n")
        md.append("|---|---|---|---|---|\n")
        for rec in report.recommendations:
            icon = "🔴" if rec.severity == "high" else "🟡"
            md.append(
                f"| {icon} {rec.severity.upper()} | {rec.category} | {rec.service} | "
                f"{rec.estimated_monthly_saving:.2f} ({rec.estimated_saving_percent:.0f}%) | "
                f"{rec.title} |\n"
            )
        md.append("\n")
        for i, rec in enumerate(report.recommendations, 1):
            md.append(f"### {i}. {rec.title}\n\n")
            md.append(f"{rec.description}\n\n")
            md.append(
                f"**Estimated monthly saving:** {rec.estimated_monthly_saving:.2f} "
                f"({rec.estimated_saving_percent:.0f}%)  \n"
                f"**Severity:** {rec.severity.upper()}  \n"
                f"**Category:** {rec.category}\n\n"
            )

    md.append("---\n\n*Generated by Azure Cost Forecasting Engine. RayStudio*\n")
    return "".join(md)


def to_html(report: CostReport) -> str:
    rec_rows = "".join(
        f"<tr><td>{'🔴' if r.severity == 'high' else '🟡'} {r.severity.upper()}</td>"
        f"<td>{_esc(r.category)}</td><td>{_esc(r.service)}</td>"
        f"<td>{r.estimated_monthly_saving:.2f}</td><td>{_esc(r.title)}</td></tr>\n"
        for r in report.recommendations
    )
    forecast_rows = "".join(
        f"<tr><td>{fr.horizon_days}d</td>"
        f"<td>{fr.projected_total:.2f}</td>"
        f"<td>{fr.projected_total_vs_baseline:+.2f}</td>"
        f"<td>{fr.trend_direction}</td></tr>\n"
        for fr in [report.forecast_30, report.forecast_60, report.forecast_90]
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Azure Cost Forecast</title>
<style>body{{font-family:sans-serif;max-width:1100px;margin:auto;padding:20px}}
h1,h2{{color:#0078d4}}table{{border-collapse:collapse;width:100%;margin-bottom:20px}}
th,td{{border:1px solid #ddd;padding:8px;text-align:left}}th{{background:#f0f0f0}}
tr:hover{{background:#f9f9f9}}.saving{{color:#107c10;font-weight:bold}}</style></head>
<body>
<h1>Azure Cost Forecasting Report</h1>
<p>Generated: {report.generated_at} | Subscription: <code>{_esc(report.subscription_id)}</code>
 | History: {report.history_days} days | Currency: {_esc(report.currency)}</p>
<h2>Historical Summary</h2>
<table><tr><th>Metric</th><th>Value</th></tr>
<tr><td>Average daily cost</td><td>{report.average_daily_cost:.2f}</td></tr>
<tr><td>Total cost ({report.history_days}d)</td><td>{report.total_historical_cost:.2f}</td></tr>
</table>
<h2>Cost Forecast</h2>
<table><tr><th>Horizon</th><th>Projected Total</th><th>vs. Baseline</th><th>Trend</th></tr>
{forecast_rows}</table>
<h2>Optimization Recommendations</h2>
<p class="saving">Total estimated monthly saving: {report.total_estimated_monthly_saving:.2f}</p>
<table><tr><th>Severity</th><th>Category</th><th>Service</th><th>Monthly Saving</th><th>Title</th></tr>
{rec_rows}</table>
<p><em>Generated by Azure Cost Forecasting Engine. RayStudio</em></p>
</body></html>"""


def _esc(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
